### ISSUE TITLE
NodeUI - UI updates and fixes

### ISSUE THREAD

**Issue by Donatas-MN** [mysteriumnetwork/node-webui#12]
- [x] Update texts here:
- Safe option: traffic vetted via business contracts and unavailable to the general public. This option potentially will give less reward.
![Pasted_Image_2022-02-21_11_37](https://user-images.githubusercontent.com/91055712/154928147-ba994ab3-715a-4ff2-9408-5253737de0b6.jpg)

- [x] With Auto withdrawals added wallet screen Beneficiary logic should be changed. It should be the simple rule, if Beneficiary for this transaction was 0x0000000000000000 then show "-", if it was anything else, then show actual address. Currently we show "-" even if Beneficiary was external wallet (with auto withdrawals ON):
![image](https://user-images.githubusercontent.com/91055712/162209644-2dec1831-6d8d-4bdd-b272-c996bb9f169b.png)

**Comment by mdomasevicius** [comment]
1.11.1-rc0

**Comment by lusine-h** [comment]
tested, everything looks good
