### ISSUE TITLE
NodeUI - Update onboarding screen for Auto withdrawals

### ISSUE THREAD

**Issue by Donatas-MN** [mysteriumnetwork/node-webui#15]
Current step:
![image](https://user-images.githubusercontent.com/91055712/161073011-00bf2318-7178-4560-bca9-e3b5c41c85dc.png)

Tasks:
- [ ] Change it to such:
![image](https://user-images.githubusercontent.com/91055712/161082259-57fee683-0c92-4967-8618-01619f65e2a0.png)

Texts:
- Add your ERC-20 Polygon compatible wallet for automatic withdrawals

- Make sure withdrawal address is from ERC-20 Polygon compatible wallet (e.g. MetaMask or MyEtherWallet)! [Check here for instructions how to setup MYST token on MetaMask](https://docs.mysterium.network/for-node-runners/payout-guide).

- [ ] Wallet address is mandatory field. User has to enter it to continue.

- [ ] Entered wallet address should be set as Beneficiary for automatic withdrawals (should be updated during registration).

**Comment by lusine-h** [comment]
Checked, works as expected.
