### ISSUE TITLE
NodeUI - Redesign

### ISSUE THREAD

**Issue by Donatas-MN** [mysteriumnetwork/node-webui#19]
Currently discussed ideas:
1. Remove step-by-step onboarding and have all required data filled in Dashboard.
2. Have separate page for handling payments for registration (currently it's modal and not very user friendly).
3. Combine T&C acceptance and Password change to the same screen.
4. ...

Next step would be to give UI/UX designer task to start thinking on how it could look like.

**Comment by Ayse-AK** [comment]
Designs are completed. Development tasks will open.
