### ISSUE TITLE
NodeUI - Update text for Paypal option in Network registration payment window

### ISSUE THREAD

**Issue by Donatas-MN** [mysteriumnetwork/node-webui#22]
Tasks:
- [ ] **Change text in Paypal 1st screen:**
![Pasted_Image_2022-04-13_15_53](https://user-images.githubusercontent.com/91055712/163184526-3ed7a06a-39e9-4cae-a4b2-c86171ee505e.jpg)

Texts:
1
To register your node on blockchain you can either transfer required amount of MYST or pay 1 USD/EUR/GBP.

2 
Pay with Paypal (1 USD/EUR/GBP)

3
You will be charged 1 USD/EUR/GBP plus applicable VAT. Please select your currency and country of residence below to proceed.

Note: After clicking NEXT below, new tab/window will be opened and you will be redirected to Paypal to complete transaction. Please be patient, registration on blockchain might take a few minutes after a successful payment transaction.

- [ ] **Change text in Paypal 2nd screen:**
![Pasted_Image_2022-04-13_15_35](https://user-images.githubusercontent.com/91055712/163181609-eff570c7-be1c-4f96-8e34-1bf3c882ce67.jpg)

**From the backed there should be a check with Pilvytis if this Identity paid the order. Ping Guillem for more details on Pilvytis implementation.**

When Pilvytis confirms that order is paid, display such:
![Pasted_Image_2022-04-13_15_35](https://user-images.githubusercontent.com/91055712/163183325-3f4cf88b-9b82-4069-a9c2-3f2ad5d45c49.jpg)

**Comment by mdomasevicius** [comment]
1.13.0-rc0

**Comment by Donatas-MN** [comment]
To fix:
- [x] Text are not correct (see issue description for correct ones):
![Pasted_Image_2022-04-27_14_12](https://user-images.githubusercontent.com/91055712/165511544-9eb7d29c-49d3-411b-91fe-16aaf4ca89f9.jpg)

- [ ] Can we hide "NEXT" button until text "Payment verification in progress (may take a few minutes).." is displayed? It's a bit confusing with both buttons present as in the beginning user need only "PAY NOW":
![image](https://user-images.githubusercontent.com/91055712/165511823-cb2671a4-0593-4792-acdc-e7cb760af9c6.png)

- [ ] Text should be "Payment verification in progress (may take a few minutes).." here:
![Pasted_Image_2022-04-27_14_17](https://user-images.githubusercontent.com/91055712/165511966-f3dd2783-10d5-4284-b9f3-990e3bd20b94.jpg)

- [ ] It takes ~2 minutes until Payment is confirmed which is pretty long for user who would expect it to be much faster (especially as Paypal payment is already done at that moment). Can we decrease waiting time? Otherwise let's change text to such: 
`Payment verification in progress (may take a few minutes)...`

![image](https://user-images.githubusercontent.com/91055712/165517712-96cc6b9a-1709-4974-b11c-f56fbeb9343e.png)

- [ ] MYST amount should be displayed as 0.2 instead of 0.20000000. In general let's use two decimal points, e.g. if needed 0.22 would be displayed:
![Pasted_Image_2022-04-27_14_06](https://user-images.githubusercontent.com/91055712/165513355-275cb9d6-b94b-4720-991c-d96c3c360e04.jpg)

**Comment by Donatas-MN** [comment]
- [ ] Should be "Pay with Paypal (1 USD/EUR/GBP)"
![Pasted_Image_2022-04-28_11_05](https://user-images.githubusercontent.com/91055712/165707227-cadb7cff-bf16-4147-a0e9-0d37f9b709dd.jpg)
