### ISSUE TITLE
NodeUI - Remove Bounty things related before MainNet release

### ISSUE THREAD

**Issue by mdomasevicius** [mysteriumnetwork/node-webui#7]
Tasks:
- [x] Update token names from MYSTT to MYST everywhere in NodeUI

- [x] Remove bounty panel from Dashboard page:
![image](https://user-images.githubusercontent.com/91055712/138663349-4303e1b9-141d-4db6-b5dc-afee5ce6795c.png)

- [x] Bounty payout panel in Settings page. Change to Default withdrawal address:
![image](https://user-images.githubusercontent.com/91055712/138663522-b54b6b3e-ec32-46c8-b227-6d5166dbb5ad.png)

- [x] Remove "Bounty payout address input" step from Node setup wizard:
![image](https://user-images.githubusercontent.com/91055712/138665124-469fa50b-f0f6-4ebf-b966-cd04250a28e6.png)

- [x] Withdrawal card - Change name from "Total earnings" to "Balance"

- [x] Add "Total earnings" card in the front:
![image](https://user-images.githubusercontent.com/91055712/138705123-4080ffb6-dedc-4cd8-a3e3-8985ba53c3ae.png)
Data is taken from Node DB (Amount from last promise)

**Comment by Donatas-MN** [comment]
Additional tasks:
- [x] Change GiB, MiB, KiB to GB, MB, KB everywhere in UI.

- [x] Change Limit bandwidth minimum and default value to 50 Mbps (in config it should be set to 6.25 MB/S as it's in MB). As current UI element does not allow to write in small caps, change to text like this:
![image](https://user-images.githubusercontent.com/91055712/138866315-70bcd12b-5f4b-4806-91fc-2d8020cd37fd.png)

- [x] Add "Unsettled earnings" card here:
![Pasted_Image_2021-10-26_12_24](https://user-images.githubusercontent.com/91055712/138850223-be46da9b-abeb-4a18-a4ac-47b2df3e5de2.png)
It's calculated "Amount" - "Settled". Check if we have "Settled" data already.

Note: if cards start not to fit the page then "Unique clients" card could be hidden for now.

- [x] Use "Default withdrawal address" in Withdrawal widget. If user adds default address then it's automatically used in Withdrawal widget.
